export const CART = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  REMOVE_ALL_FROM_CART: 'REMOVE_ALL_FROM_CART',
  DECREASE_QUANTITY_CART: 'DECREASE_QUANTITY_CART',
  INCREASE_QUANTITY_CART: 'INCREASE_QUANTITY_CART'
}

export const WISHLIST = {
  ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
  REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST'
}

export const SHOP = {
  SET_FILTER_CATEGORY: 'SET_FILTER_CATEGORY',
  SET_FILTER_PRICE_RANGE: 'SET_FILTER_PRICE_RANGE',
  SET_FILTER_BRAND: 'SET_FILTER_BRAND',
  RESET_FILTER: 'RESET_FILTER'
}

export const USER = {
  SET_USER_TOKEN: 'SET_USER_TOKEN',
  USER_SIGN_OUT: 'USER_SIGN_OUT',
  RECEIVE_USER: 'RECEIVE_USER',
  REGISTER_USER: 'REGISTER_USER',
  LOAD_DATA_SUCCESS: 'LOAD_DATA_SUCCESS',
  USER_INFO: 'USER_INFO',
  REGISTER_USER_FLAG: 'REGISTER_USER_FLAG',
  USER_ERROR: 'USER_ERROR',
  LOGIN_USER: 'LOGIN_USER'
}
